[project]
name = "seven-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "esika", email = "esikataheri9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "dotenv>=0.9.9",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.5",
]

[project.scripts]
seven-shop = "seven_shop:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
